eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9002/service-registry/eureka/

server:
  port: 9011
  servlet:
    context-path: /prashanavali

spring:
  profiles:
    active: default
  datasource:
    url: jdbc:mysql://localhost:3306/gavayam_prashanavali?noAccessToProcedureBodies=true&autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: "optional:configserver:http://localhost:9001/gconfigserver"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: none
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


logging:
  file:
    name: /home/uulin/gavayam/${spring.application.name}.log
    path: /home/uulin/
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %log{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %log{36} - %msg%n"
  level:
    root: info
    org:
      springframework:
        web: debug
        security: debug
        jpa: debug
        data: debug
        oauth2: debug
      hibernate:
        SQL: off
    com:
      gavayam: debug

